Repository liquidprompt/liquidprompt, pull requests merged in 2023-02, with the labels that each got.

#668 Add hyperlinks for directories in path
  docs/config.rst
  docs/functions/util.rst
  docs/overview.rst
  liquidprompt
  tests/test_acpi.sh
  tests/test_connection.sh
  tests/test_sysfs.sh
  tests/test_tools.sh
  tests/test_utils.sh
Labels: enhancement, path, reviews wanted

#766 feat(devenv): adds Modules support
  docs/config.rst
  liquidprompt
  tests/test_env.sh
Labels: enhancement

#769 fix(theme-preview): adds a fake SSH_CONNECTION
  tools/theme-preview.sh
Labels: bug
